# Generated by Django 4.2.7 on 2023-12-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_educationteacher_imageteacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationteacher',
            options={'verbose_name': 'Учитель'},
        ),
    ]
