# Generated by Django 4.2.7 on 2023-12-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productUrl',
            field=models.TextField(blank=True),
        ),
    ]
