# Generated by Django 4.2.7 on 2023-12-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_educationteacher_imageteacher'),
        ('products', '0002_product_producturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='educationTeacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='teacher.educationteacher'),
            preserve_default=False,
        ),
    ]
